class_name UpgradeLibrary
extends Resource
## Every upgrade in the game (src/upgrades/data/upgrade_library.tres,
## generated by tools/gen_upgrades.py).

@export var upgrades: Array[UpgradeData] = []


func find(id: StringName) -> UpgradeData:
	for u in upgrades:
		if u.id == id:
			return u
	return null
